Repository alibaba/GraphScope, pull requests merged in 2022-07, with the labels that each got.

#1786 [Gaia/IR] Return json with possible error message in `print_plan_as_json`
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java
  research/query_service/ir/core/src/plan/ffi.rs
Labels: component:gie, component:gaia

#1817 [GIE/IR] Fix IR warnings
  research/query_service/ir/core/src/plan/logical.rs
  research/query_service/ir/core/src/plan/meta.rs
  research/query_service/ir/runtime/src/assembly.rs
Labels: component:gie, component:gaia

#1852 [IR Runtime] support mean() in runtime
  research/dyn_type/src/object.rs
  research/query_service/ir/runtime/src/process/operator/accum/accum.rs
Labels: component:gaia

#1859 [GAIA] Make input data as generic data types in `JobAssembly` interface
  research/engine/pegasus/server/examples/echo_service.rs
  research/engine/pegasus/server/src/cluster/standalone.rs
  research/engine/pegasus/server/src/job.rs
  research/engine/pegasus/server/src/rpc.rs
  research/query_service/ir/runtime/src/assembly.rs
Labels: component:gaia

#1847 [GAIA-IR] support more patterns of aggregate functions, i.e min/max/toList/toSet/avg/countDistinct
  research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/ArgAggFn.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/graph/RemoteTestGraph.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/ParserUtils.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/ExprArg.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransform.java
  research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransformFactory.java
  research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/AggregateStepTest.java
  research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/ValueMapTest.java
  research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
  research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/subtask/GroupStepTest.java
  research/query_service/ir/core/src/plan/logical.rs
  research/query_service/ir/core/src/plan/meta.rs
Labels: wip
